import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Selfie from '../public/pic_of_ole.jpg'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>
          Ole sin portofolio
        </title>
        <meta
          name="description"
          content="Generated by create next app" 
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1" 
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <header>
        <h1>
          Ole Håvard Furuseth Bergan
        </h1>
        <h2>
          Frontend utvikler
        </h2>
      </header>
      <main>
        <section 
          className=' bg-cardBG text-greyText w-64 py-6'
        >
          <p>
            &lt;
            <span 
                className=' text-pinkText'
            >
              Developer
            </span>
          </p>
          <p>
            id=
          </p>
          <p 
            className=' text-blueText'
          >
            "Ole Håvard
          </p>
          <p 
            className=' text-blueText'
          >
            Furuseth Bergan"
          </p>
          <p>
            className=
          </p>
          <p 
            className=' text-blueText'
          >
            "Frontend Developer"
          </p>
          <p>
            &lt;
              <span 
                className=' text-pinkText'
              >
                Developer
              </span>
            &gt;
          </p>
          <Image
            src={Selfie}
            width={146}
          />
          <p>
            &lt;/ 
              <span 
                className=' text-pinkText'
              >
                Developer
              </span>
            &gt;
          </p>
        </section>
      </main>
    </>
  )
}